apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbvu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nbvu
  template:
    metadata:
      labels:
        app: nbvu
    spec:
      containers:
      - image: okteto.dev/nbvu:latest
        name: nbvu
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "93505008-040d-11ed-b939-0242ac120002"
        - name: Vless_Path
          value: "/vlsx555"
        - name: Vmess_UUID
          value: "93505008-040d-11ed-b939-0242ac120002"
        - name: Vmess_Path
          value: "/vm6gv66"
        - name: Share_Path
          value: "/v2link"
